name: Sync Upstream

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/SzeMeng76/LunaTV.git || true

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Automated sync from upstream"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main

      - name: Clean History
        if: always()
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 2

